- name: myplay1
  hosts: localhost
  become: true
  connection: local
  tasks:
    - name: create file
      file:
        name: myfile.txt
        state: touch
    - name: create directory
      file:
        name: mydir
        state: directory
    - name: copy fileto directory
      copy:
        src: myfile.txt
        dest: mydir/
